### PR TITLE
Add schemas for $JETTON lockup root and promise wallet

### PR DESCRIPTION
**Pull request by somewallet**

### CODE REVIEW

**Comment by mr-tron** [comment]
Hi. Can you give an example of contract? We need it for writing tests

**Comment by somewallet** [comment]
You can find Jetton Lockup Root & Jetton Lockup wallet in [this repo](https://github.com/JetTon-Bot/jt-ico-smc/tree/dev_2)

**Comment by mr-tron** [comment]
Sorry, maybe I chose bad formulation. I asked about deployed contracts in mainnet or testnet

**Comment by somewallet** [comment]
> Sorry, maybe I chose bad formulation. I asked about deployed contracts in mainnet or testnet

This is Jetton Lockup Root in mainnet:

https://tonviewer.com/EQDMtd3SED38RezeGUA4iQREKhlGPy3gDbHV9110GiUC1I03

**Comment by mr-tron** [comment]
Sorry for big latency with answer. I tried to find these method in this contract (or jetton_walets contracts) and they don't work. Also contract has verified code and it doesn't contain these methods.

**Comment by mr-tron** [comment]
Maybe you updated contract code?

**Pull request closed without merging**
